import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const SFPROROUNDED = localFont({
  src: [
    {
      path: "../public/fonts/SF-Pro-Rounded-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Heavy.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Thin.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/SF-Pro-Rounded-Ultralight.otf",
      weight: "100",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Mac OS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SFPROROUNDED.className} overflow-hidden antialiased w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
